#!/bin/sh
# Build the 32 native ARM WineD3D island objects that Box86 links in, together
# with the per-translation-unit native-target registries.
#
# BUILD.md described this as a shell snippet and nothing checked it in, so the
# exact flags had to be reconstructed once. Keep the recipe here instead.
#
# The objects go straight into box86-src/src/island/, where patch 09's
# CMakeLists glob picks them up as prebuilt EXTERNAL_OBJECTs.
#
# -fshort-wchar is required: without it four files fail on L"..." literals,
# because Windows WCHAR is two bytes and Linux wchar_t is four.
#
# TWO PASSES, AND WHY IT IS NOT A FIXPOINT
# ========================================
#
# Pass 1 compiles the sources as-is, purely so the generator can read which
# names each translation unit defines. Pass 2 recompiles each source with its
# generated registry fragment appended, which takes the address of every
# mappable function -- 916 of them are `static` and are not reachable from any
# other TU, which is why the fragment has to be inside the TU rather than in one
# central file.
#
# This terminates by construction and must not be confused with the
# rebuild-until-stable loop it replaced. Symbol IDs depend on function NAMES
# only. Appending the registry adds data objects and changes no name, so pass 2
# cannot invalidate the input pass 1 produced. The old loop existed because the
# table stored ADDRESSES read back out of the linked binary, which every rebuild
# moved; nothing in this build reads an address any more.
set -eu

HERE=$(cd "$(dirname "$0")" && pwd)
REPO=$(cd "$HERE/../../.." && pwd)
if [ -r "$REPO/.env" ]; then
    set -a
    # shellcheck disable=SC1091
    . "$REPO/.env"
    set +a
fi
WORKSPACE="${MGS2_WORKSPACE:-$(dirname "$REPO")}"
WINE_SRC="${WINE_SRC:-$WORKSPACE/recovered-session/wine-11.0}"
WINE_BUILD="${WINE_BUILD:-$WORKSPACE/recovered-session/build-wine-i386}"
BOX86_SRC="${BOX86_SRC:-$WORKSPACE/box86-src}"
SYSROOT="${SYSROOT:?set SYSROOT to the extracted armhf cross sysroot}"
CC="${CC:-arm-linux-gnueabihf-gcc}"
# EXTRA_CFLAGS exists for one reason: building the island with an ARM compiler
# that assigns the guest's MSVC field offsets. GCC has no ARM -mms-bitfields, so
# the whole island is built by Clang when that layout is required:
#
#   CC=clang-18 EXTRA_CFLAGS="--target=arm-linux-gnueabihf -mms-bitfields" \
#       SYSROOT=/ ./build_island_objects.sh
#
# Mixing compilers inside one island is NOT a supported configuration: a single
# closure would then hold two different aggregate layouts. Build every object
# with one compiler and let island_native_compiler_audit.py prove it.
EXTRA_CFLAGS="${EXTRA_CFLAGS:-}"
OUT="$BOX86_SRC/src/island"
REG="$OUT/registry"

# The i386 DLL supplies the guest RVAs. The opengl32 DLL must be the one MOUNTED
# ON THE DEVICE: the reference wineprefix copy shares an ImageBase and has
# different RVAs, which is what made the first class-C failure silent.
GUEST_DLL="${GUEST_DLL:-$WINE_BUILD/dlls/wined3d/i386-windows/wined3d.dll}"
GUEST_GL="${GUEST_GL:-}"
CLASS_C_HEADER="${CLASS_C_HEADER:-$BOX86_SRC/src/mgs2_island_class_b.h}"

INC="-I$WINE_BUILD/dlls/wined3d -I$WINE_SRC/dlls/wined3d -I$WINE_SRC/include \
     -I$WINE_SRC/include/msvcrt -I$WINE_SRC/libs/vkd3d/include \
     -I$WINE_SRC/libs/vkd3d/include/private -I$WINE_BUILD/include"
DEF="-DMGS2_RELEASE -DMGS2_FINALPLAY -D_UCRT -D__WINESRC__ -DMGS2_ISLAND_ARM \
     -DWINE_NO_TRACE_MSGS -DWINE_NO_DEBUG_MSGS $EXTRA_CFLAGS"

mkdir -p "$OUT" "$REG"

# ---- pass 1: names only -----------------------------------------------------
n=0
for f in "$WINE_SRC"/dlls/wined3d/*.c; do
    o="$OUT/$(basename "$f" .c).o"
    # shellcheck disable=SC2086
    "$CC" --sysroot="$SYSROOT" -O2 -fshort-wchar -c "$f" $INC $DEF -o "$o"
    n=$((n + 1))
done
echo "pass 1: built $n island objects (names only)"

# ---- generate the table and the per-TU registries ---------------------------
rm -f "$REG"/*.h
GEN_ARGS="$GUEST_DLL --objects $OUT --registry $REG -o $BOX86_SRC/src/mgs2_island_class_b.h"
if [ -n "$GUEST_GL" ]; then
    GEN_ARGS="$GEN_ARGS --opengl32 $GUEST_GL"
elif [ -r "$CLASS_C_HEADER" ]; then
    # The mounted opengl32.dll is a separate device artifact and is not kept in
    # this repository. Preserve its already-verified fallback table exactly;
    # emitting zero class-C entries would make an unrelated WineD3D rebuild
    # silently lose 379 mappings.
    GEN_ARGS="$GEN_ARGS --preserve-class-c-from $CLASS_C_HEADER"
fi
# shellcheck disable=SC2086
python3 "$HERE/gen_class_b_table.py" $GEN_ARGS

# ---- the entry identities, from the SAME DLL -------------------------------
#
# This was missing, and it had been shipping. class_b.h was regenerated by every
# island build while mgs2_island_entry_identity.h was not regenerated by any of
# them -- so it kept whatever DLL it was last generated against by hand. On
# 2026-08-23 the header still held p72c's RVAs (2026-08-22) while fp12, fp13 and
# fp14 had all shipped since: 0 of its 44 RVAs matched any of those three DLLs.
#
# Box86's identity rule is module base + canonical RVA, with the marker as a
# witness, and it correctly REFUSES a mismatch. So the refusal was silent and
# total: on the first run that looked, 14 of the 19 armed ids -- including entry
# 10 (measured -8.87 ms/frame), entry 4 (-2.68), entry 23 (-1.94) and entry 41,
# the fused draw-state root -- printed "NOT armed" and stayed emulated. 881
# refusals, 0 successes.
#
# gen_entry_identity.py's own docstring says it: "an entry's RVA must come from
# the DLL being mounted, not from a rebuild". Being generated in the same step as
# class_b.h, from $GUEST_DLL, is what makes that true by construction rather than
# by somebody remembering.
#
# --require-id limits the out-of-window control to the ids production actually
# arms, and the list is read out of the launcher rather than typed here -- the
# same reason the release manifest is generated from its mount_bind lines. Without
# it the tool exits 1 over ids 11 and 34, which no configuration arms, and under
# `set -e` that aborted this script BEFORE pass 2: the header was written, the
# island objects were not rebuilt, and the build looked like it had succeeded.
ISLAND_LAUNCHER="${MGS2_ISLAND_LAUNCHER:-$REPO/device/launch-play-wined3d-fp15.sh}"
ISLAND_ONLY=$(sed -n 's/^export MGS2_BOX86_ISLAND_ONLY="\${MGS2_BOX86_ISLAND_ONLY:-\([0-9,]*\)}"/\1/p' \
    "$ISLAND_LAUNCHER")
[ -n "$ISLAND_ONLY" ] || {
    echo "cannot read MGS2_BOX86_ISLAND_ONLY from $ISLAND_LAUNCHER" >&2
    exit 1
}
IDENT_ARGS=""
for id in $(echo "$ISLAND_ONLY" | tr ',' ' '); do
    IDENT_ARGS="$IDENT_ARGS --require-id $id"
done
# shellcheck disable=SC2086
python3 "$HERE/gen_entry_identity.py" "$GUEST_DLL" $IDENT_ARGS \
    -o "$BOX86_SRC/src/mgs2_island_entry_identity.h" >/dev/null
echo "entry identities regenerated from $(basename "$GUEST_DLL") for armed ids $ISLAND_ONLY"

# ---- pass 2: same sources, with the registry appended -----------------------
# The wrapper includes the original source so the registry sees its statics.
# Nothing in the Wine tree is edited for this.
WRAP="$OUT/wrappers"
mkdir -p "$WRAP"
rm -f "$WRAP"/*.c
n=0
for f in "$WINE_SRC"/dlls/wined3d/*.c; do
    b=$(basename "$f" .c)
    w="$WRAP/$b.c"
    {
        printf '/* Generated wrapper: the source, then its native-target registry.\n'
        printf ' * The registry must be inside this TU -- most of its targets are static. */\n'
        printf '#include "%s"\n' "$f"
        [ -r "$REG/$b.h" ] && printf '#include "%s"\n' "$REG/$b.h"
    } > "$w"
    # shellcheck disable=SC2086
    "$CC" --sysroot="$SYSROOT" -O2 -fshort-wchar -c "$w" $INC $DEF -I"$OUT" -o "$OUT/$b.o"
    n=$((n + 1))
done
echo "pass 2: rebuilt $n island objects with registries"

# ---- layout witness --------------------------------------------------------
# The island objects carry no DWARF, so the compiler's own flag string cannot be
# read back from them. Bake the decisive sizes into the object set instead: this
# is what the compiler ACTUALLY laid out, not what a command line asked for.
# island_native_compiler_audit.py reads these four words and refuses a build
# whose layout is not the one the ABI audit admitted.
cat > "$OUT/layout_witness.c" <<'WITNESS'
/* Generated by build_island_objects.sh. Do not hand-edit. */
#include "wined3d_private.h"

const unsigned int mgs2_island_layout_witness[] = {
    0x4d475332u,                                /* "MGS2" */
    (unsigned int)sizeof(struct texture_stage_op),
    (unsigned int)sizeof(struct ffp_frag_settings),
    (unsigned int)sizeof(struct ffp_frag_desc),
    (unsigned int)sizeof(struct wined3d_context),
    (unsigned int)sizeof(struct wined3d_state),
};
WITNESS
# shellcheck disable=SC2086
"$CC" --sysroot="$SYSROOT" -O2 -fshort-wchar -c "$OUT/layout_witness.c" $INC $DEF \
    -o "$OUT/layout_witness.o"
echo "layout witness built"

# ---- control checks ---------------------------------------------------------
# The island entry marker is an x86 NOP; in the ARM build its bytes would sit in
# the instruction stream, where 0x474d decodes as `bx r9`. MGS2_ISLAND_MARK is
# #ifdef __i386__ so nothing should match here. If this fires, every marked
# function branches to a garbage address before running any of its own body --
# which is exactly what the 2026-08-15 crash was.
if grep -rlq $'\x0f\x1f\x84\x00\x4d\x47\x53' "$OUT"/*.o 2>/dev/null; then
    echo "FAIL: x86 island marker bytes present in the ARM objects" >&2
    exit 1
fi
echo "control check passed: no x86 marker bytes in the ARM objects"

# Every ID the generator emitted must actually be registered by an object, or
# the resolver would call through a null. Counting here rather than trusting the
# generator's own arithmetic: the section is what the linker will see.
want=$(sed -n 's/^#define MGS2_NATIVE_ID_COUNT \([0-9]*\)$/\1/p' \
    "$BOX86_SRC/src/mgs2_island_class_b.h")
got=$(python3 - "$OUT" <<'PYEOF'
import glob, os, subprocess, sys
# Section size / sizeof(struct mgs2_native_reg). Read from the objects rather
# than trusting the generator's own arithmetic: the section is what the linker
# will actually see. (awk's strtonum is a gawk extension; this box has mawk.)
total = 0
for obj in sorted(glob.glob(os.path.join(sys.argv[1], "*.o"))):
    out = subprocess.run(["readelf", "-SW", obj], capture_output=True, text=True).stdout
    for line in out.splitlines():
        f = line.replace("[", " ").replace("]", " ").split()
        if "mgs2_native_ids" in f:
            i = f.index("mgs2_native_ids")
            total += int(f[i + 4], 16)
print(total // 8)
PYEOF
)
if [ "$want" != "$got" ]; then
    echo "FAIL: $want native IDs generated but $got registered in the objects" >&2
    exit 1
fi
echo "control check passed: all $want native IDs registered by the objects"

# CMake lists these prebuilt .o files as EXTERNAL_OBJECT inputs, but does not
# track their mtimes as link dependencies. Without a normal source becoming
# newer, `cmake --build` can leave the previous island inside box86 even though
# every object above was replaced (observed as 1124/1612 IDs at runtime). Make
# the bridge TU newer so the next build necessarily recompiles one cheap source
# and relinks against the just-built objects.
touch "$BOX86_SRC/src/mgs2_island_bridges.c"
echo "relink trigger updated: mgs2_island_bridges.c"
