#!/usr/bin/env python3
"""Generate Box86 bridge signatures for the WineD3D public API.

The island's boundary is wined3d's own exported API: wined3d.spec exports 372
entry points and d3d8 uses 146 of them. Those 146 are the forward bridges. They
are not written by hand -- the prototypes in include/wine/wined3d.h carry enough
type information to derive box86's signature letters mechanically, and a missing
or wrong signature is an ABI bug that would only show as a crash at runtime.

Letters follow box86's wrapper convention:
    v void   i int   u unsigned   f float   d double   L 64-bit   p pointer

Run from the Wine source root. Output goes to stdout.
"""
import re, sys, pathlib

root = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else ".")
spec = (root / "dlls/wined3d/wined3d.spec").read_text()
exports = set(re.findall(r"^\s*@\s+(?:cdecl|stdcall)\s+(\w+)", spec, re.M))
d3d8 = " ".join(p.read_text(errors="replace") for p in (root / "dlls/d3d8").glob("*.c"))
used = {e for e in exports if re.search(r"\b" + re.escape(e) + r"\s*\(", d3d8)}
hdr = (root / "include/wine/wined3d.h").read_text(errors="replace")

def letter(t):
    t = t.strip()
    if t in ("void", ""): return "v"
    if "*" in t: return "p"
    if "float" in t: return "f"
    if "double" in t: return "d"
    if re.search(r"\b(UINT64|ULONGLONG|LONGLONG|uint64_t|int64_t)\b", t): return "L"
    if re.search(r"\b(unsigned|UINT|DWORD|ULONG|BOOL|uint32_t|size_t)\b", t): return "u"
    return "i"

sig, missing = {}, []
for name in sorted(used):
    m = re.search(r"([A-Za-z_][\w \*]*?)\b" + re.escape(name) + r"\s*\(([^;{]*)\)\s*(?:DECLSPEC\w*)?\s*;",
                  hdr, re.S)
    if not m:
        missing.append(name); continue
    args = [a for a in re.split(r",(?![^(]*\))", m.group(2)) if a.strip() and a.strip() != "void"]
    sig[name] = letter(m.group(1)) + "F" + "".join(letter(a) for a in args)

print("/* generated by gen_bridge_table.py -- do not edit */")
for n, s in sorted(sig.items()):
    print(f"GO({n}, {s})")
print(f"/* {len(sig)} of {len(used)} derived; {len(missing)} missing */", file=sys.stderr)
if missing:
    print("/* MISSING: " + " ".join(missing) + " */", file=sys.stderr)
    raise SystemExit(1)
