/* Auto-generated abort stubs for the native ARM WineD3D island.
 * Win32/GDI entry points from context creation, swapchain and cursor code,
 * plus WineD3D parts that stay on the x86 side. Reaching one means the island
 * was routed where it does not belong, so each aborts loudly.
 * No system headers: the list is generated from undefined symbols and would
 * collide with real libc prototypes. */
extern int printf(const char *, ...);
extern void abort(void);

static void mgs2_island_forbidden(const char *n)
{
    printf("MGS2 island: forbidden call to %s\n", n);
    abort();
}

void BitBlt(void) { mgs2_island_forbidden("BitBlt"); }
void CallNextHookEx(void) { mgs2_island_forbidden("CallNextHookEx"); }
void CallWindowProcA(void) { mgs2_island_forbidden("CallWindowProcA"); }
void CallWindowProcW(void) { mgs2_island_forbidden("CallWindowProcW"); }
void ChoosePixelFormat(void) { mgs2_island_forbidden("ChoosePixelFormat"); }
void CreateBitmap(void) { mgs2_island_forbidden("CreateBitmap"); }
void CreateCompatibleDC(void) { mgs2_island_forbidden("CreateCompatibleDC"); }
void CreateIconIndirect(void) { mgs2_island_forbidden("CreateIconIndirect"); }
void CreateWindowExA(void) { mgs2_island_forbidden("CreateWindowExA"); }
void D3DKMTCloseAdapter(void) { mgs2_island_forbidden("D3DKMTCloseAdapter"); }
void D3DKMTCreateDCFromMemory(void) { mgs2_island_forbidden("D3DKMTCreateDCFromMemory"); }
void D3DKMTDestroyDCFromMemory(void) { mgs2_island_forbidden("D3DKMTDestroyDCFromMemory"); }
void D3DKMTOpenAdapterFromGdiDisplayName(void) { mgs2_island_forbidden("D3DKMTOpenAdapterFromGdiDisplayName"); }
void DebugBreak(void) { mgs2_island_forbidden("DebugBreak"); }
void DefWindowProcA(void) { mgs2_island_forbidden("DefWindowProcA"); }
void DefWindowProcW(void) { mgs2_island_forbidden("DefWindowProcW"); }
void DeleteCriticalSection(void) { mgs2_island_forbidden("DeleteCriticalSection"); }
void DeleteDC(void) { mgs2_island_forbidden("DeleteDC"); }
void DeleteObject(void) { mgs2_island_forbidden("DeleteObject"); }
void DescribePixelFormat(void) { mgs2_island_forbidden("DescribePixelFormat"); }
void DestroyCursor(void) { mgs2_island_forbidden("DestroyCursor"); }
void DestroyWindow(void) { mgs2_island_forbidden("DestroyWindow"); }
void DisableThreadLibraryCalls(void) { mgs2_island_forbidden("DisableThreadLibraryCalls"); }
void EnterCriticalSection(void) { mgs2_island_forbidden("EnterCriticalSection"); }
void EnumDisplayDevicesW(void) { mgs2_island_forbidden("EnumDisplayDevicesW"); }
void FindResourceA(void) { mgs2_island_forbidden("FindResourceA"); }
void FreeResource(void) { mgs2_island_forbidden("FreeResource"); }
void GetClientRect(void) { mgs2_island_forbidden("GetClientRect"); }
void GetCursorPos(void) { mgs2_island_forbidden("GetCursorPos"); }
void GetDC(void) { mgs2_island_forbidden("GetDC"); }
void GetDesktopWindow(void) { mgs2_island_forbidden("GetDesktopWindow"); }
void GetModuleFileNameA(void) { mgs2_island_forbidden("GetModuleFileNameA"); }
void GetModuleHandleA(void) { mgs2_island_forbidden("GetModuleHandleA"); }
void GetModuleHandleExA(void) { mgs2_island_forbidden("GetModuleHandleExA"); }
void GetMonitorInfoW(void) { mgs2_island_forbidden("GetMonitorInfoW"); }
void GetObjectA(void) { mgs2_island_forbidden("GetObjectA"); }
void GetPixelFormat(void) { mgs2_island_forbidden("GetPixelFormat"); }
void GetProcAddress(void) { mgs2_island_forbidden("GetProcAddress"); }
void GetWindowLongA(void) { mgs2_island_forbidden("GetWindowLongA"); }
void GetWindowLongW(void) { mgs2_island_forbidden("GetWindowLongW"); }
void GetWindowThreadProcessId(void) { mgs2_island_forbidden("GetWindowThreadProcessId"); }
void InitializeCriticalSectionEx(void) { mgs2_island_forbidden("InitializeCriticalSectionEx"); }
void IntersectRect(void) { mgs2_island_forbidden("IntersectRect"); }
void IsBadStringPtrA(void) { mgs2_island_forbidden("IsBadStringPtrA"); }
void IsWindowUnicode(void) { mgs2_island_forbidden("IsWindowUnicode"); }
void LeaveCriticalSection(void) { mgs2_island_forbidden("LeaveCriticalSection"); }
void LoadCursorA(void) { mgs2_island_forbidden("LoadCursorA"); }
void LoadIconA(void) { mgs2_island_forbidden("LoadIconA"); }
void LoadImageA(void) { mgs2_island_forbidden("LoadImageA"); }
void LoadResource(void) { mgs2_island_forbidden("LoadResource"); }
void LockResource(void) { mgs2_island_forbidden("LockResource"); }
void MonitorFromWindow(void) { mgs2_island_forbidden("MonitorFromWindow"); }
void NtDelayExecution(void) { mgs2_island_forbidden("NtDelayExecution"); }
void QueryPerformanceCounter(void) { mgs2_island_forbidden("QueryPerformanceCounter"); }
void QueryPerformanceFrequency(void) { mgs2_island_forbidden("QueryPerformanceFrequency"); }
void RegCloseKey(void) { mgs2_island_forbidden("RegCloseKey"); }
void RegOpenKeyA(void) { mgs2_island_forbidden("RegOpenKeyA"); }
void RegQueryValueExA(void) { mgs2_island_forbidden("RegQueryValueExA"); }
void RegisterClassA(void) { mgs2_island_forbidden("RegisterClassA"); }
void ReleaseDC(void) { mgs2_island_forbidden("ReleaseDC"); }
void ScreenToClient(void) { mgs2_island_forbidden("ScreenToClient"); }
void SelectObject(void) { mgs2_island_forbidden("SelectObject"); }
void SetCursor(void) { mgs2_island_forbidden("SetCursor"); }
void SetCursorPos(void) { mgs2_island_forbidden("SetCursorPos"); }
void SetDIBColorTable(void) { mgs2_island_forbidden("SetDIBColorTable"); }
void SetPixelFormat(void) { mgs2_island_forbidden("SetPixelFormat"); }
void SetWindowLongA(void) { mgs2_island_forbidden("SetWindowLongA"); }
void SetWindowLongW(void) { mgs2_island_forbidden("SetWindowLongW"); }
void SetWindowPos(void) { mgs2_island_forbidden("SetWindowPos"); }
void SetWindowsHookExW(void) { mgs2_island_forbidden("SetWindowsHookExW"); }
void SizeofResource(void) { mgs2_island_forbidden("SizeofResource"); }
void SystemParametersInfoW(void) { mgs2_island_forbidden("SystemParametersInfoW"); }
void TlsAlloc(void) { mgs2_island_forbidden("TlsAlloc"); }
void TlsFree(void) { mgs2_island_forbidden("TlsFree"); }
void TlsGetValue(void) { mgs2_island_forbidden("TlsGetValue"); }
void TlsSetValue(void) { mgs2_island_forbidden("TlsSetValue"); }
void UnhookWindowsHookEx(void) { mgs2_island_forbidden("UnhookWindowsHookEx"); }
void UnregisterClassA(void) { mgs2_island_forbidden("UnregisterClassA"); }
void WindowFromDC(void) { mgs2_island_forbidden("WindowFromDC"); }
void __stdio_common_vsprintf(void) { mgs2_island_forbidden("__stdio_common_vsprintf"); }
void __stdio_common_vsscanf(void) { mgs2_island_forbidden("__stdio_common_vsscanf"); }
void __wine_dbg_get_channel_flags(void) { mgs2_island_forbidden("__wine_dbg_get_channel_flags"); }
void __wine_dbg_header(void) { mgs2_island_forbidden("__wine_dbg_header"); }
void __wine_dbg_output(void) { mgs2_island_forbidden("__wine_dbg_output"); }
void __wine_dbg_strdup(void) { mgs2_island_forbidden("__wine_dbg_strdup"); }
void _assert(void) { mgs2_island_forbidden("_assert"); }
void _fdclass(void) { mgs2_island_forbidden("_fdclass"); }
void _putenv(void) { mgs2_island_forbidden("_putenv"); }
void _recalloc(void) { mgs2_island_forbidden("_recalloc"); }
void _stricmp(void) { mgs2_island_forbidden("_stricmp"); }
void adapter_adjust_mapped_memory(void) { mgs2_island_forbidden("adapter_adjust_mapped_memory"); }
void adapter_adjust_memory(void) { mgs2_island_forbidden("adapter_adjust_memory"); }
void adapter_vk_copy_bo_address(void) { mgs2_island_forbidden("adapter_vk_copy_bo_address"); }
void atoi(void) { mgs2_island_forbidden("atoi"); }
void calloc(void) { mgs2_island_forbidden("calloc"); }
void cosf(void) { mgs2_island_forbidden("cosf"); }
void expf(void) { mgs2_island_forbidden("expf"); }
void floorf(void) { mgs2_island_forbidden("floorf"); }
void free(void) { mgs2_island_forbidden("free"); }
void getenv(void) { mgs2_island_forbidden("getenv"); }
void glDisable(void) { mgs2_island_forbidden("glDisable"); }
void glEnable(void) { mgs2_island_forbidden("glEnable"); }
void isspace(void) { mgs2_island_forbidden("isspace"); }
void lstrcmpiW(void) { mgs2_island_forbidden("lstrcmpiW"); }
void magLookup(void) { mgs2_island_forbidden("magLookup"); }
void malloc(void) { mgs2_island_forbidden("malloc"); }
void memchr(void) { mgs2_island_forbidden("memchr"); }
void memcmp(void) { mgs2_island_forbidden("memcmp"); }
void memcpy(void) { mgs2_island_forbidden("memcpy"); }
void memmove(void) { mgs2_island_forbidden("memmove"); }
void memset(void) { mgs2_island_forbidden("memset"); }
void mgs2_island_ffp_enabled(void) { mgs2_island_forbidden("mgs2_island_ffp_enabled"); }
void mgs2_island_ffp_target(void) { mgs2_island_forbidden("mgs2_island_ffp_target"); }
void mgs2_p38_bypass(void) { mgs2_island_forbidden("mgs2_p38_bypass"); }
void mgs2_p38_close(void) { mgs2_island_forbidden("mgs2_p38_close"); }
void mgs2_p38_gl_draw(void) { mgs2_island_forbidden("mgs2_p38_gl_draw"); }
void mgs2_p38_hint(void) { mgs2_island_forbidden("mgs2_p38_hint"); }
void mgs2_p38_hint_dirty(void) { mgs2_island_forbidden("mgs2_p38_hint_dirty"); }
void mgs2_submit_census_gl_draw(void) { mgs2_island_forbidden("mgs2_submit_census_gl_draw"); }
void minMipLookup(void) { mgs2_island_forbidden("minMipLookup"); }
void modf(void) { mgs2_island_forbidden("modf"); }
void powf(void) { mgs2_island_forbidden("powf"); }
void realloc(void) { mgs2_island_forbidden("realloc"); }
void strcat(void) { mgs2_island_forbidden("strcat"); }
void strcmp(void) { mgs2_island_forbidden("strcmp"); }
void strlen(void) { mgs2_island_forbidden("strlen"); }
void strpbrk(void) { mgs2_island_forbidden("strpbrk"); }
void strrchr(void) { mgs2_island_forbidden("strrchr"); }
void strstr(void) { mgs2_island_forbidden("strstr"); }
void strtoul(void) { mgs2_island_forbidden("strtoul"); }
void swapchain_set_max_frame_latency(void) { mgs2_island_forbidden("swapchain_set_max_frame_latency"); }
void vk_access_mask_from_buffer_usage(void) { mgs2_island_forbidden("vk_access_mask_from_buffer_usage"); }
void vk_pipeline_stage_mask_from_buffer_usage(void) { mgs2_island_forbidden("vk_pipeline_stage_mask_from_buffer_usage"); }
void vkd3d_shader_build_varying_map(void) { mgs2_island_forbidden("vkd3d_shader_build_varying_map"); }
void vkd3d_shader_compile(void) { mgs2_island_forbidden("vkd3d_shader_compile"); }
void vkd3d_shader_free_dxbc(void) { mgs2_island_forbidden("vkd3d_shader_free_dxbc"); }
void vkd3d_shader_free_messages(void) { mgs2_island_forbidden("vkd3d_shader_free_messages"); }
void vkd3d_shader_free_scan_descriptor_info(void) { mgs2_island_forbidden("vkd3d_shader_free_scan_descriptor_info"); }
void vkd3d_shader_free_scan_signature_info(void) { mgs2_island_forbidden("vkd3d_shader_free_scan_signature_info"); }
void vkd3d_shader_free_shader_code(void) { mgs2_island_forbidden("vkd3d_shader_free_shader_code"); }
void vkd3d_shader_parse_dxbc(void) { mgs2_island_forbidden("vkd3d_shader_parse_dxbc"); }
void vkd3d_shader_scan(void) { mgs2_island_forbidden("vkd3d_shader_scan"); }
void vkd3d_utils_set_log_callback(void) { mgs2_island_forbidden("vkd3d_utils_set_log_callback"); }
void wglCreateContext(void) { mgs2_island_forbidden("wglCreateContext"); }
void wglDeleteContext(void) { mgs2_island_forbidden("wglDeleteContext"); }
void wglGetCurrentContext(void) { mgs2_island_forbidden("wglGetCurrentContext"); }
void wglGetCurrentDC(void) { mgs2_island_forbidden("wglGetCurrentDC"); }
void wglGetProcAddress(void) { mgs2_island_forbidden("wglGetProcAddress"); }
void wglMakeCurrent(void) { mgs2_island_forbidden("wglMakeCurrent"); }
void wglShareLists(void) { mgs2_island_forbidden("wglShareLists"); }
void wined3d_adapter_cleanup(void) { mgs2_island_forbidden("wined3d_adapter_cleanup"); }
void wined3d_adapter_init(void) { mgs2_island_forbidden("wined3d_adapter_init"); }
void wined3d_adapter_vk_get_memory_type_index(void) { mgs2_island_forbidden("wined3d_adapter_vk_get_memory_type_index"); }
void wined3d_bo_slab_vk_unmap(void) { mgs2_island_forbidden("wined3d_bo_slab_vk_unmap"); }
void wined3d_cs_create(void) { mgs2_island_forbidden("wined3d_cs_create"); }
void wined3d_cs_destroy(void) { mgs2_island_forbidden("wined3d_cs_destroy"); }
void wined3d_cs_destroy_object(void) { mgs2_island_forbidden("wined3d_cs_destroy_object"); }
void wined3d_cs_emit_add_dirty_texture_region(void) { mgs2_island_forbidden("wined3d_cs_emit_add_dirty_texture_region"); }
void wined3d_cs_emit_clear(void) { mgs2_island_forbidden("wined3d_cs_emit_clear"); }
void wined3d_cs_emit_decode(void) { mgs2_island_forbidden("wined3d_cs_emit_decode"); }
void wined3d_cs_emit_preload_resource(void) { mgs2_island_forbidden("wined3d_cs_emit_preload_resource"); }
void wined3d_cs_emit_set_color_key(void) { mgs2_island_forbidden("wined3d_cs_emit_set_color_key"); }
void wined3d_cs_emit_unload_resource(void) { mgs2_island_forbidden("wined3d_cs_emit_unload_resource"); }
void wined3d_cs_init_object(void) { mgs2_island_forbidden("wined3d_cs_init_object"); }
void wined3d_cs_map_bo_address(void) { mgs2_island_forbidden("wined3d_cs_map_bo_address"); }
void wined3d_decref(void) { mgs2_island_forbidden("wined3d_decref"); }
void wined3d_device_context_emit_blt_sub_resource(void) { mgs2_island_forbidden("wined3d_device_context_emit_blt_sub_resource"); }
void wined3d_device_context_emit_clear_rendertarget_view(void) { mgs2_island_forbidden("wined3d_device_context_emit_clear_rendertarget_view"); }
void wined3d_device_context_emit_clear_uav(void) { mgs2_island_forbidden("wined3d_device_context_emit_clear_uav"); }
void wined3d_device_context_emit_copy_uav_counter(void) { mgs2_island_forbidden("wined3d_device_context_emit_copy_uav_counter"); }
void wined3d_device_context_emit_draw(void) { mgs2_island_forbidden("wined3d_device_context_emit_draw"); }
void wined3d_device_context_emit_execute_command_list(void) { mgs2_island_forbidden("wined3d_device_context_emit_execute_command_list"); }
void wined3d_device_context_emit_generate_mipmaps(void) { mgs2_island_forbidden("wined3d_device_context_emit_generate_mipmaps"); }
void wined3d_device_context_emit_map(void) { mgs2_island_forbidden("wined3d_device_context_emit_map"); }
void wined3d_device_context_emit_reset_state(void) { mgs2_island_forbidden("wined3d_device_context_emit_reset_state"); }
void wined3d_device_context_emit_set_blend_state(void) { mgs2_island_forbidden("wined3d_device_context_emit_set_blend_state"); }
void wined3d_device_context_emit_set_constant_buffers(void) { mgs2_island_forbidden("wined3d_device_context_emit_set_constant_buffers"); }
void wined3d_device_context_emit_set_depth_stencil_state(void) { mgs2_island_forbidden("wined3d_device_context_emit_set_depth_stencil_state"); }
void wined3d_device_context_emit_set_depth_stencil_view(void) { mgs2_island_forbidden("wined3d_device_context_emit_set_depth_stencil_view"); }
void wined3d_device_context_emit_set_extra_ps_args(void) { mgs2_island_forbidden("wined3d_device_context_emit_set_extra_ps_args"); }
void wined3d_device_context_emit_set_extra_vs_args(void) { mgs2_island_forbidden("wined3d_device_context_emit_set_extra_vs_args"); }
void wined3d_device_context_emit_set_feature_level(void) { mgs2_island_forbidden("wined3d_device_context_emit_set_feature_level"); }
void wined3d_device_context_emit_set_index_buffer(void) { mgs2_island_forbidden("wined3d_device_context_emit_set_index_buffer"); }
void wined3d_device_context_emit_set_light(void) { mgs2_island_forbidden("wined3d_device_context_emit_set_light"); }
void wined3d_device_context_emit_set_light_enable(void) { mgs2_island_forbidden("wined3d_device_context_emit_set_light_enable"); }
void wined3d_device_context_emit_set_predication(void) { mgs2_island_forbidden("wined3d_device_context_emit_set_predication"); }
void wined3d_device_context_emit_set_rasterizer_state(void) { mgs2_island_forbidden("wined3d_device_context_emit_set_rasterizer_state"); }
void wined3d_device_context_emit_set_render_state(void) { mgs2_island_forbidden("wined3d_device_context_emit_set_render_state"); }
void wined3d_device_context_emit_set_rendertarget_views(void) { mgs2_island_forbidden("wined3d_device_context_emit_set_rendertarget_views"); }
void wined3d_device_context_emit_set_samplers(void) { mgs2_island_forbidden("wined3d_device_context_emit_set_samplers"); }
void wined3d_device_context_emit_set_scissor_rects(void) { mgs2_island_forbidden("wined3d_device_context_emit_set_scissor_rects"); }
void wined3d_device_context_emit_set_shader(void) { mgs2_island_forbidden("wined3d_device_context_emit_set_shader"); }
void wined3d_device_context_emit_set_shader_resource_views(void) { mgs2_island_forbidden("wined3d_device_context_emit_set_shader_resource_views"); }
void wined3d_device_context_emit_set_stream_outputs(void) { mgs2_island_forbidden("wined3d_device_context_emit_set_stream_outputs"); }
void wined3d_device_context_emit_set_stream_sources(void) { mgs2_island_forbidden("wined3d_device_context_emit_set_stream_sources"); }
void wined3d_device_context_emit_set_texture(void) { mgs2_island_forbidden("wined3d_device_context_emit_set_texture"); }
void wined3d_device_context_emit_set_texture_state(void) { mgs2_island_forbidden("wined3d_device_context_emit_set_texture_state"); }
void wined3d_device_context_emit_set_unordered_access_views(void) { mgs2_island_forbidden("wined3d_device_context_emit_set_unordered_access_views"); }
void wined3d_device_context_emit_set_vertex_declaration(void) { mgs2_island_forbidden("wined3d_device_context_emit_set_vertex_declaration"); }
void wined3d_device_context_emit_set_viewports(void) { mgs2_island_forbidden("wined3d_device_context_emit_set_viewports"); }
void wined3d_device_context_emit_unmap(void) { mgs2_island_forbidden("wined3d_device_context_emit_unmap"); }
void wined3d_device_context_emit_update_sub_resource(void) { mgs2_island_forbidden("wined3d_device_context_emit_update_sub_resource"); }
void wined3d_device_context_push_constants(void) { mgs2_island_forbidden("wined3d_device_context_push_constants"); }
void wined3d_device_context_set_depth_bounds(void) { mgs2_island_forbidden("wined3d_device_context_set_depth_bounds"); }
void wined3d_driver_info_init(void) { mgs2_island_forbidden("wined3d_driver_info_init"); }
void wined3d_get_device_caps(void) { mgs2_island_forbidden("wined3d_get_device_caps"); }
void wined3d_get_gpu_description(void) { mgs2_island_forbidden("wined3d_get_gpu_description"); }
void wined3d_get_user_override_gpu_description(void) { mgs2_island_forbidden("wined3d_get_user_override_gpu_description"); }
void wined3d_gpu_from_feature_level(void) { mgs2_island_forbidden("wined3d_gpu_from_feature_level"); }
void wined3d_incref(void) { mgs2_island_forbidden("wined3d_incref"); }
void wined3d_init(void) { mgs2_island_forbidden("wined3d_init"); }
void wined3d_null_parent_ops(void) { mgs2_island_forbidden("wined3d_null_parent_ops"); }
void wined3d_output_get_desc(void) { mgs2_island_forbidden("wined3d_output_get_desc"); }
void wined3d_swapchain_activate(void) { mgs2_island_forbidden("wined3d_swapchain_activate"); }
void wined3d_swapchain_get_display_mode(void) { mgs2_island_forbidden("wined3d_swapchain_get_display_mode"); }
void wined3d_swapchain_get_gamma_ramp(void) { mgs2_island_forbidden("wined3d_swapchain_get_gamma_ramp"); }
void wined3d_swapchain_get_raster_status(void) { mgs2_island_forbidden("wined3d_swapchain_get_raster_status"); }
void wined3d_swapchain_gl_cleanup(void) { mgs2_island_forbidden("wined3d_swapchain_gl_cleanup"); }
void wined3d_swapchain_gl_get_context(void) { mgs2_island_forbidden("wined3d_swapchain_gl_get_context"); }
void wined3d_swapchain_gl_init(void) { mgs2_island_forbidden("wined3d_swapchain_gl_init"); }
void wined3d_swapchain_present(void) { mgs2_island_forbidden("wined3d_swapchain_present"); }
void wined3d_swapchain_resize_buffers(void) { mgs2_island_forbidden("wined3d_swapchain_resize_buffers"); }
void wined3d_swapchain_set_gamma_ramp(void) { mgs2_island_forbidden("wined3d_swapchain_set_gamma_ramp"); }
void wined3d_swapchain_set_window(void) { mgs2_island_forbidden("wined3d_swapchain_set_window"); }
void wined3d_swapchain_state_set_fullscreen(void) { mgs2_island_forbidden("wined3d_swapchain_state_set_fullscreen"); }
void wined3d_swapchain_state_setup_fullscreen(void) { mgs2_island_forbidden("wined3d_swapchain_state_setup_fullscreen"); }
