/* generated: island entry id, symbol, box86 signature */
MGS2_ISLAND_ENTRY(0, context_invalidate_compute_state, vFpu)
MGS2_ISLAND_ENTRY(1, context_invalidate_state, vFpu)
MGS2_ISLAND_ENTRY(2, debug_d3dformat, pFi)
MGS2_ISLAND_ENTRY(3, device_invalidate_state, vFpu)
MGS2_ISLAND_ENTRY(4, mgs2_batch_flush, vF)
MGS2_ISLAND_ENTRY(5, mgs2_submit_census_gl_draw, vFuu)
MGS2_ISLAND_ENTRY(6, multiply_matrix, vFppp)
MGS2_ISLAND_ENTRY(7, wined3d_buffer_acquire_bo_for_write, vFpp)
MGS2_ISLAND_ENTRY(8, wined3d_buffer_get_memory, uFppp)
MGS2_ISLAND_ENTRY(9, wined3d_buffer_invalidate_location, vFpu)
MGS2_ISLAND_ENTRY(10, wined3d_buffer_load, vFppp)
MGS2_ISLAND_ENTRY(11, wined3d_buffer_load_location, uFppu)
MGS2_ISLAND_ENTRY(12, wined3d_buffer_load_sysmem, pFpp)
MGS2_ISLAND_ENTRY(13, wined3d_context_gl_enable_clip_distances, vFpu)
MGS2_ISLAND_ENTRY(14, wined3d_debug_location, pFu)
MGS2_ISLAND_ENTRY(15, wined3d_device_context_blt, iFppuppupupi)
MGS2_ISLAND_ENTRY(16, wined3d_device_context_emit_blt_sub_resource, vFppuppupupi)
MGS2_ISLAND_ENTRY(17, wined3d_ffp_get_fs_settings, vFppp)
MGS2_ISLAND_ENTRY(18, wined3d_format_calculate_pitch, vFpuuupp)
MGS2_ISLAND_ENTRY(19, wined3d_format_convert_from_float, vFppp)
MGS2_ISLAND_ENTRY(20, wined3d_light_state_get_light, pFpu)
MGS2_ISLAND_ENTRY(21, wined3d_release_dc, vFii)
MGS2_ISLAND_ENTRY(22, wined3d_rendertarget_view_invalidate_location, vFpu)
MGS2_ISLAND_ENTRY(23, wined3d_rendertarget_view_load_location, vFppu)
MGS2_ISLAND_ENTRY(24, wined3d_rendertarget_view_prepare_location, vFppu)
MGS2_ISLAND_ENTRY(25, wined3d_rendertarget_view_validate_location, vFpu)
MGS2_ISLAND_ENTRY(26, wined3d_resource_check_box_dimensions, iFpup)
MGS2_ISLAND_ENTRY(27, wined3d_resource_free_sysmem, vFp)
MGS2_ISLAND_ENTRY(28, wined3d_resource_memory_colour_fill, vFppppi)
MGS2_ISLAND_ENTRY(29, wined3d_stream_info_from_declaration, vFppp)
MGS2_ISLAND_ENTRY(30, wined3d_swapchain_set_window, iFpi)
MGS2_ISLAND_ENTRY(31, wined3d_texture_add_dirty_region, iFpup)
MGS2_ISLAND_ENTRY(32, wined3d_texture_from_resource, pFp)
MGS2_ISLAND_ENTRY(33, wined3d_texture_invalidate_location, vFpuu)
MGS2_ISLAND_ENTRY(34, wined3d_texture_load_location, uFpupu)
MGS2_ISLAND_ENTRY(35, wined3d_texture_prepare_location, uFpupu)
MGS2_ISLAND_ENTRY(36, wined3d_texture_validate_location, vFpuu)
/* The post-batching DRAW boundary: both CS_OP_DRAW and CS_OP_DRAW_BATCH
 * converge here.  Queue dispatch and packet decoding remain guest x86. */
MGS2_ISLAND_ENTRY(37, mgs2_cs_exec_draw_one_island, vFpuup)
/* p68 correctness boundary: guest owns context acquisition and draw state. */
MGS2_ISLAND_ENTRY(38, mgs2_draw_primitive_arrays_island, vFp)
/* p69 correctness boundary: guest owns current-context establishment. */
MGS2_ISLAND_ENTRY(39, mgs2_context_apply_draw_state_island, vFp)
